#!/usr/bin/env python

import sys
import re
import lxml.etree as etree

NS = {
    "svg": "http://www.w3.org/2000/svg",
    "inkscape": "http://www.inkscape.org/namespaces/inkscape"
}

svg = etree.parse(sys.argv[1])
wanted = sys.argv[2]

for layer in svg.xpath("//svg:g[@inkscape:groupmode='layer' and @inkscape:label]", namespaces=NS):
    label = layer.xpath("@inkscape:label", namespaces=NS)[0]
    flags = set(re.split(" *, *", label))
    if wanted in flags:
        layer.set("style", "display:inline")
    else:
        layer.getparent().remove(layer)

print etree.tostring(svg)
